### ISSUE TITLE
uSync 8.7- Release Testing

### ISSUE THREAD

**Issue by KevinJump** [KevinJump/uSync8#119]
Feature checklist for the 8.7.0 release of uSync.

This issue is tracking our internal shakedown testing of the next release of uSync due out before Umbraco 8.7 becomes a thing.

**n.b items with ~~strikethrough~~ are now moving to 8.6.4 release**

## Features
- [x] Everything still works with the dependency checkers removed from core #118 
- [x] ~~chain-able mappers #126~~
- [x] ~~Culture Filters imports (only some languages) #48 #115~~ 
- [x] ~~Relations Handler tracks relation types & relations #92~~
- [x] ~~Scheduled content publishes/unpublishes as expected #125~~ 
- [x] Check Bento Editor support finds dependencies #140 
- [x] Custom value mapping config works. #149 

## Issues
- [x] ~~Don't save DTGE Temp blueprint files #117~~
- [x] JSON formatting indents for NestedContent #116

## Breaking changes 
This release has some breaking changes for any code inheriting our base classes.

- [x] ~~Changes to ContentBaseHandler constructor~~
- [x] ~~Obsoleted Constructors in SyncBaseHandler~~
- [x] ~~Obsoleted methods in Serializers (should now use methods that pass the options in)~~
- [x] ~~Trackers are now loaded in a collection so do need to be registred in a composer~~
- [x] ~~dependency checkers are now loaded in a collection so don't need to be registered in a composer~~
- [x] the base dependency checkers have been removed from this project (and put in uSync.Complete) as they are not used by the core uSync tools #118 
- [x] ~~remove the base dependency on IEntity #123~~

## Backward Compatability 
- [x] workout what will/won't work for any existing code that references core classes/interfaces
(we might have an unfixible breaking change in the removal of the Dependency Items from the core)

**Comment by KevinJump** [comment]
Pre-release bugs : 

- [x] tracker doesn't show schedule changes when content is scheduled. 
- [x] if a content item is published, and scheduled for the future it gets unpublished

**Comment by KevinJump** [comment]
- [x] Installing uSync.ContentEdition 8.6.3 and upgrading uSync to 8.7.x will now work (although we will not recommend this!)

**Comment by KevinJump** [comment]
## Basic setup

### New Site
- [x] Clean install doesn't break anything
- [x] Installed before Umbraco is setup doesn't break anything 
- [x] Export works
- [x] Report doesn't detect any changes
- [x] Import doesn't detect any changes 
- [x] Full Import imports everything 
- [x] Restart Site 
  - [x] Report after restart doesn't detect any changes 
  - [x] Import after restart doesn't detect any changes 

### Upgrade 
- [x] Upgrading site from previous doesn't break site
- [x] All files are updated
- [x] javascript/css cache is broken if needed
- [x] Report has no changes (point release)
- [x] Import doesn't import anything
- [x] Full Import still works
- [x] Export works. 

### Site clone 
- [x] New empty site with uSync installed (no starter kit)
- [x] Copy of folders (App_Plugins/css/scripts/views/media/uSync)
	- [x] Import imports everything (except for contact - missing dll)
	- [x] report only reports items dependeny on maps.
	- [x] Copy the map dll from bin
	- [x] Import imports the missing item 
	- [x] Report details no changes between sites 
	
### Deletion
- [x] Removal of Datatype 
- [x] Removal of DocType
- [x] Removal of Content
- [x] Removal of Media 

### Creation
- [x] New Datatype copied as expected
- [x] New Doctype copied as expected
- [x] New Content Item copied as expected
- [x] New Media item copied as expected 

### Updates
- [x] update to Datatype copied as expected
- [x] update to Doctype copied as expected
- [x] update to Content Item copied as expected
- [x] update to Media item copied as expected 

### Cultures (create welsh homepage on source)
- [x] Language is created on target
- [x] Content for language is created on target 
- [x] Content is published as expected

### Scheduling 
- [x] Scheduled content is copied over to the new site
- [x] Scheduled release in the past results in published item
- [x] Scheduled expire in the past results in unpublished item
- [x] Scheule of one language works as expected

### uSync.Complete (Backwards compatability)
- [x] Confirm that the current uSync.Complete checklist works with this version
