### ISSUE TITLE
uSync 8.6.4 Release testing

### ISSUE THREAD

**Issue by KevinJump** [KevinJump/uSync8#132]
Umbraco 8.7 will be awesome, but it isn't coming quickly. 

there are a number of fixes/enhancements awaiting release in the uSync 8.7 branch that are not breaking, so we are going to port them from the uSync 8.7 release into a uSync 8.6.4 release to get them out the door, and hopefully reduce the complexity of the uSync 8.7 release when it comes to all thew new Umbraco stuff. 

## Features
- [x] #126 chain value mappers in the collection, so you can have multiple mappers
- [x] #122 remove dependency on IEntity in Interfaces
- [x] #135 remove dependency on IEntity in base classes.
- [x] #125 Speed enhancements on content/media imports
- [x] #92 RelationType Handler
- [x] #136 ISyncOptionsSerializer 
   - [x] #115 Filter exports/imports by culture (partial publishing).
   - [x] #92 Relation type handler support for turning relations on/off
- [x] #113 Tracker collections - multiple trackers per property / item type
- [x] #105 Dependency collections - multiple dependency checkers per item

## Fixes
- [x] #117 don't save DTGE temp content templates
- [x] #112 better defaults when the usync8.config handlers are missing
- [x] #128 improved support for non-routed media when using azure provider 
- [x] #133 datatypes starting with number can overwrite .config files when saving.

**Comment by KevinJump** [comment]
removed some of the breaking change elements (like JSON formatting of Nested content) so this can 'just' be a minor patch release.

**Comment by KevinJump** [comment]
We have managed to push quite a few of the "breaking change" updated from v8.7 into 8.6.4 as non-breaking, (mainly through new constructors and the use of the `obsolete` attribute. 

As such this update has a lot in it for a point release. ;)

**Comment by KevinJump** [comment]
Checklist : 

## Basic setup

### New Site
- [x] Clean install doesn't break anything
- [x] Installed before Umbraco is setup doesn't break anything 
- [x] Export works
- [x] Report doesn't detect any changes
- [x] Import doesn't detect any changes 
- [x] Full Import imports everything 
- [x] Restart Site 
  - [x] Report after restart doesn't detect any changes 
  - [x] Import after restart doesn't detect any changes 

### Upgrade 
- [x] Upgrading site from previous doesn't break site
- [x] All files are updated
- [x] javascript/css cache is broken if needed
- [x] Report has no changes (point release)
- [x] Import doesn't import anything
- [x] Full Import still works
- [x] Export works. 

### Site clone 
- [x] New empty site with uSync installed (no starter kit)
- [x] Copy of folders (App_Plugins/css/scripts/views/media/uSync)
	- [x] Import imports everything (except for contact - missing dll)
	- [x] report only reports items dependeny on maps.
	- [x] Copy the map dll from bin
	- [x] Import imports the missing item 
	- [x] Report details no changes between sites 
	
### Deletion
- [x] Removal of Datatype 
- [x] Removal of DocType
- [x] Removal of Content
- [x] Removal of Media 

### Creation
- [x] New Datatype copied as expected
- [x] New Doctype copied as expected
- [x] New Content Item copied as expected
- [x] New Media item copied as expected 

### Updates
- [x] update to Datatype copied as expected
- [x] update to Doctype copied as expected
- [x] update to Content Item copied as expected
- [x] update to Media item copied as expected 

### Cultures (create welsh homepage on source)
- [x] Language is created on target
- [x] Content for language is created on target 
- [x] Content is published as expected

### Scheduling 
- [x] Scheduled content is copied over to the new site
- [x] Scheduled release in the past results in published item
- [x] Scheduled expire in the past results in unpublished item
- [x] Scheule of one language works as expected

### uSync.Complete (Backwards compatability)
- [x] Confirm that the current uSync.Complete checklist works with this version

**Comment by KevinJump** [comment]
### known issue
- [x] Still have an issue where MemberType guid's change inside umbraco on restart :( 
- [x] media deletes are getting reported every sync even when the media has been deleted 
- [x] check scheduled times are being stored in correct format inside xml

**Comment by KevinJump** [comment]
Fix for member type issue #142

**Comment by KevinJump** [comment]
fix da56a7fa7e30638428ce2233d806171a19bd3646 to ensure date times are consistent for scheduled publish things.

**Comment by KevinJump** [comment]
Complete : ✔️ ⭐
