### ISSUE TITLE
8.10.0 - release checklist. 

### ISSUE THREAD

**Issue by KevinJump** [KevinJump/uSync8#273]
v8.10.0 - release - checklist - all green = go for release. 

# uSync checklist 

This is in addtion to any automated testing/etc (although it would be nice to automate this to). checklist of pre-release tests - to make sure things work as we expect them to in the 'real' world. 

### New Site
- [x] Clean install doesn't break anything
- [x] Installed before Umbraco is setup doesn't break anything 
- [x] Export works
- [x] Report doesn't detect any changes
- [x] Import doesn't detect any changes 
- [x] Full Import imports everything 
- [x] Restart Site 
  - [x] Report after restart doesn't detect any changes 
  - [x] Import after restart doesn't detect any changes 

### Upgrade 
- [x] Upgrading site from previous doesn't break site
- [x] All files are updated
- [x] javascript/css cache is broken if needed
- [x] Report has no changes (point release)
- [x] Import doesn't import anything
- [x] Full Import still works
- [x] Export works. 

### Site clone 
- [x] New empty site with uSync installed (no starter kit)
- [ ] Copy of folders (App_Plugins/css/scripts/views/media/uSync)
	- [x] Import imports everything (except for contact - missing dll)
	- [x] report only reports items dependeny on maps.
	- [x] Copy the map dll from bin
	- [x] Import imports the missing item 
	- [x] Report details no changes between sites 
	
### Deletion
- [x] Removal of Datatype 
- [x] Removal of DocType
- [x] Removal of Content
- [x] Removal of Media 

### Creation
- [x] New Datatype copied as expected
- [x] New Doctype copied as expected
- [x] New Content Item copied as expected
- [x] New Media item copied as expected 

### Updates
- [x] update to Datatype copied as expected
- [x] update to Doctype copied as expected
- [x] update to Content Item copied as expected
- [x] update to Media item copied as expected 

### Cultures (create welsh homepage on source)
- [x] Language is created on target
- [x] Content for language is created on target 
- [x] Content is published as expected

### Scheduling 
- [x] Scheduled content is copied over to the new site
- [x] Scheduled release in the past results in published item
- [x] Scheduled expire in the past results in unpublished item
- [x] Scheule of one language works as expected

### uSync.Complete (Backwards compatability)
- [x] Confirm that the current uSync.Complete checklist works with this version

**Comment by KevinJump** [comment]
Redding Weddy.
